siteTitle="Article Archive"
baseColor = "#884499"
linkPrefix = "/learning_links"
docPages = [
  "/docs/",
  "/docs/functional-programming/",
  "/docs/javascript/",
  "/docs/some-react-code/",
  "/docs/system-design/",
  "/docs/web/",
]
