siteTitle="AlphabetJS"
baseColor = "#884499"
linkPrefix = "/gatsby-starter-documentation"
docPages = [
  "/docs/",
  "/docs/functional-programming/",
  "/docs/javascript/",
  "/docs/some-react-code/",
  "/docs/system-design/",
  "/docs/web/",
]
